yyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyyyyyyyyyyyy

diff --git a/.github/workflows/dockertest.yml b/.github/workflows/dockertest.yml
--- a/.github/workflows/dockertest.yml
+++ b/.github/workflows/dockertest.yml
@@ -145,12 +145,28 @@ jobs:
       TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
     steps:
       -
+        name: Install prerequisites
+        run: |
+          # shellcheck shell=sh
+          set -eu
+          apk add curl jq npm gcompat unzip
+          npm install -g "@microsoft/sarif-multitool@${MICROSOFT_SARIF_MULTITOOL_VERSION}"
+          # Specify the sinon version to use.
+          # Remove sinon from this line when sinon 16.1.2 (or later) is released, or when using MITRE_SAF_VERSION that includes https://github.com/mitre/saf/pull/1919
+          npm install -g sinon@16.1.0 "@mitre/saf@${MITRE_SAF_VERSION}"
+      -
         name: Scan image
         uses: aquasecurity/trivy-action@0.24.0
         with:
           image-ref: ${{ env.IMAGE_NAME }}
-          format: 'table'
-          output: 'trivy-results.table'
+          format: 'json'
+          output: 'trivy-results.json'
+      -
+        name: Make the JSON into a CSV
+        run: |
+          set -eu
+          saf convert trivy2hdf -i trivy-results.json -o trivy-results.hdf
+          saf convert hdf2csv -i trivy-results.json -o trivy-results.csv
       -
         name: Upload reports
         if: success() || failure() # always run even if the previous step fails
@@ -158,7 +174,7 @@ jobs:
         with:
           name: trivy-results
           path: |
-            trivy-results.table
+            trivy-results.csv
 
   #snyk:
   #  needs: build
@@ -172,45 +188,45 @@ jobs:
   #      with:
   #        image: ${{ env.IMAGE_NAME }}
 
-  clam:
-    needs: build
-    permissions:
-      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
-      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
-    runs-on: ubuntu-latest
-    env:
-      EXPORT_NAME: "build.tar"
-      DIR_NAME: "build"
-    steps:
-      -
-        name: Start ClamAV daemon
-        uses: toblux/start-clamd-github-action@v0.2.1
-        with:
-          db_main: 'true'
-          db_daily: 'true'
-      -
-        name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ vars.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
-        name: Create, export, then extract to the filesystem
-        run: |
-          set -eu
-          mkdir -p ${{ env.DIR_NAME }}
-          CONT_ID=$(docker create ${{ env.IMAGE_NAME }})
-          docker export ${CONT_ID} -o ${{ env.EXPORT_NAME }}
-          tar --exclude='dev/null' --exclude='dev/random' --exclude='dev/urandom' --exclude='dev/zero' -xvf ${{ env.EXPORT_NAME }} -C ${{ github.workspace }}/${{ env.DIR_NAME }}
-      -
-        name: Scan using ClamAV to ensure no malware in static images
-        run: |
-          clamscan -ir ${{ github.workspace }}/${{ env.DIR_NAME }} > results.txt
-      -
-        name: Upload reports
-        if: success() || failure() # always run even if the previous step fails
-        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
-        with:
-          name: clamd-results
-          path: |
-            results.txt
+  #clam:
+  #  needs: build
+  #  permissions:
+  #    security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
+  #    actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
+  #  runs-on: ubuntu-latest
+  #  env:
+  #    EXPORT_NAME: "build.tar"
+  #    DIR_NAME: "build"
+  #  steps:
+  #    -
+  #      name: Start ClamAV daemon
+  #      uses: toblux/start-clamd-github-action@v0.2.1
+  #      with:
+  #        db_main: 'true'
+  #        db_daily: 'true'
+  #    -
+  #      name: Login to Docker Hub
+  #      uses: docker/login-action@v3
+  #      with:
+  #        username: ${{ vars.DOCKERHUB_USERNAME }}
+  #        password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #    -
+  #      name: Create, export, then extract to the filesystem
+  #      run: |
+  #        set -eu
+  #        mkdir -p ${{ env.DIR_NAME }}
+  #        CONT_ID=$(docker create ${{ env.IMAGE_NAME }})
+  #        docker export ${CONT_ID} -o ${{ env.EXPORT_NAME }}
+  #        tar --exclude='dev/null' --exclude='dev/random' --exclude='dev/urandom' --exclude='dev/zero' -xvf ${{ env.EXPORT_NAME }} -C ${{ github.workspace }}/${{ env.DIR_NAME }}
+  #    -
+  #      name: Scan using ClamAV to ensure no malware in static images
+  #      run: |
+  #        clamscan -ir ${{ github.workspace }}/${{ env.DIR_NAME }} > results.txt
+  #    -
+  #      name: Upload reports
+  #      if: success() || failure() # always run even if the previous step fails
+  #      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
+  #      with:
+  #        name: clamd-results
+  #        path: |
+  #          results.txt
