bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbb

diff --git a/.github/workflows/dockertest.yml b/.github/workflows/dockertest.yml
--- a/.github/workflows/dockertest.yml
+++ b/.github/workflows/dockertest.yml
@@ -88,7 +88,6 @@ jobs:
   #        oscap-docker image "${IMAGE_NAME}" xccdf eval --verbose ERROR --fetch-remote-resources --profile "xccdf_basic_profile_.check" --results "openscap-report.xml" --report "openscap-report.html" "${SSG_DIR}/stigs-${WOLFI_STIG_VERSION}/gpos/xml/scap/ssg/content/ssg-chainguard-gpos-ds.xml"
   #        OSCAP_EXIT_CODE=$?
   #        set -e
-
   #        case "${OSCAP_EXIT_CODE}" in
   #          0)
   #            echo "All rules passed"
@@ -114,6 +113,25 @@ jobs:
   #        name: openscap-reports
   #        path: |
   #          openscap-report.xml
+
+  grype:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      -
+        name: Scan image
+        uses: anchore/scan-action@v5.0.1
+        id: grypescan
+        with:
+          registry-username: ${{ vars.DOCKERHUB_USERNAME }}
+          registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
+          image: ${{ env.IMAGE_NAME }}
+          fail-build: false
+      -
+        name: upload Anchore scan SARIF report
+        uses: github/codeql-action/upload-sarif@v2
+        with:
+          sarif_file: ${{ steps.grypescan.outputs.sarif }}
 
 
   #grype:
@@ -247,58 +265,58 @@ jobs:
   #      with:
   #        image: ${{ env.IMAGE_NAME }}
 
-  snyk:
-    needs: build
-    runs-on: ubuntu-latest
-    env:
-      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-      MITRE_SAF_VERSION: "1.4.14"
-    steps:
-      -
-        name: Install prerequisites
-        run: |
-          set -eu
-          curl --compressed https://downloads.snyk.io/cli/stable/snyk-linux -o snyk
-          sudo chmod +x ./snyk
-          sudo mv ./snyk /usr/local/bin/
-          sudo apt-get install -y npm
-          # Specify the sinon version to use.
-          # Remove sinon from this line when sinon 16.1.2 (or later) is released, or when using MITRE_SAF_VERSION that includes https://github.com/mitre/saf/pull/1919
-          npm install -g sinon@16.1.0 "@mitre/saf@${MITRE_SAF_VERSION}"
-      -
-        name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ vars.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-#snyk container test ${{ env.IMAGE_NAME }} --app-vulns --nested-jars-depth=5 --json --json-file-output=snyk-output.json
-      -
-        name: Scan using Snyk
-        continue-on-error: true
-        run: |
-          snyk container test redhat/ubi9:9.4 --app-vulns --nested-jars-depth=5 --json --json-file-output=snyk-output.json || true
-      -
-        name: Make the Snyk JSON file into an HDF file
-        run: |
-          set -eu
-          saf convert snyk2hdf -i snyk-output.json -o snyk-output.hdf.json
-      # Converting HDF to CSV is currently busted,
-      # https://github.com/mitre/saf/issues/2925 for more info.
-      -
-        name: Make the HDF file into a CSV
-        run: |
-          set -eu
-          saf convert hdf2csv -i snyk-output.hdf.json -o snyk-output.csv
-      -
-        name: Upload reports
-        if: success() || failure() # always run even if the previous step fails
-        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
-        with:
-          name: snyk-results
-          path: |
-            snyk-output.json
-            snyk-output.hdf.json
-            snyk-output.csv
+  #snyk:
+  #  needs: build
+  #  runs-on: ubuntu-latest
+  #  env:
+  #    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+  #    MITRE_SAF_VERSION: "1.4.14"
+  #  steps:
+  #    -
+  #      name: Install prerequisites
+  #      run: |
+  #        set -eu
+  #        curl --compressed https://downloads.snyk.io/cli/stable/snyk-linux -o snyk
+  #        sudo chmod +x ./snyk
+  #        sudo mv ./snyk /usr/local/bin/
+  #        sudo apt-get install -y npm
+  #        # Specify the sinon version to use.
+  #        # Remove sinon from this line when sinon 16.1.2 (or later) is released, or when using MITRE_SAF_VERSION that includes https://github.com/mitre/saf/pull/1919
+  #        npm install -g sinon@16.1.0 "@mitre/saf@${MITRE_SAF_VERSION}"
+  #    -
+  #      name: Login to Docker Hub
+  #      uses: docker/login-action@v3
+  #      with:
+  #        username: ${{ vars.DOCKERHUB_USERNAME }}
+  #        password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #    -
+  #      name: Scan using Snyk
+  #      continue-on-error: true
+  #      run: |
+  #        snyk container test ${{ env.IMAGE_NAME }} --app-vulns --nested-jars-depth=5 --json --json-file-output=snyk-output.json || true
+  #    -
+  #      name: Make the Snyk JSON file into an HDF file
+  #      run: |
+  #        set -eu
+  #        saf convert snyk2hdf -i snyk-output.json -o snyk-output.hdf.json
+  #    # Converting HDF to CSV is currently busted,
+  #    # https://github.com/mitre/saf/issues/2925 for more info.
+  #    #-
+  #    #  name: Make the HDF file into a CSV
+  #    #  run: |
+  #    #    set -eu
+  #    #    saf convert hdf2csv -i snyk-output.hdf.json -o snyk-output.csv
+  #    -
+  #      name: Upload reports
+  #      if: success() || failure() # always run even if the previous step fails
+  #      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
+  #      with:
+  #        name: snyk-results
+  #        path: |
+  #          snyk-output.json
+  #          snyk-output.hdf.json
+  #          snyk-output.csv
+
   #clam:
   #  needs: build
   #  permissions:
