rrrrrrrrrrrrrrrrrr
rrrrrrrrrrrr

diff --git a/.github/workflows/dockertest.yml b/.github/workflows/dockertest.yml
--- a/.github/workflows/dockertest.yml
+++ b/.github/workflows/dockertest.yml
@@ -72,4 +72,75 @@ jobs:
           # oscap-docker requires the image to have been pulled
           docker pull "${IMAGE_NAME}"
       - name: Reveal your secrets
-        run: ls -latr ${SSG_DIR}
+        run: ls -latr ${SSG_DIR}/stigs-${WOLFI_STIG_VERSION}/gpos/xml/scap/ssg/content/
+      - name: Run openscap
+        run: |
+          # shellcheck shell=sh
+          set -eu
+          # extract /etc/os-release
+          container_id=$(docker create "${IMAGE_NAME}")
+          if ! docker export "${container_id}" | tar -tvf - | grep -E '\setc/os-release( ->.*)?$' > /dev/null 2>&1 ; then
+            >&2 echo "The operating system used by ${IMAGE_NAME} could not be detected."
+            >&2 echo "Images that are not based on an operating system (such as distroless images) cannot be scanned by SCAP."
+            exit 1
+          fi
+          docker cp -L "$container_id:/etc/os-release" .
+          docker rm "$container_id"
+          unset container_id
+          set +e
+          oscap-docker image "${IMAGE_NAME}" xccdf eval --verbose ERROR --fetch-remote-resources --profile "xccdf_basic_profile_.check" --results "openscap-report.xml" --report "openscap-report.html" "${SSG_DIR}/${SSG_DIR}/stigs-${WOLFI_STIG_VERSION}/gpos/xml/scap/ssg/content/ssg-chainguard-gpos-ds.xml"
+          OSCAP_EXIT_CODE=$?
+          set -e
+
+          case "${OSCAP_EXIT_CODE}" in
+            0)
+              echo "All rules passed"
+            ;;
+            1)
+              >&2 echo "An error occurred during evaluation"
+              exit 2
+            ;;
+            2)
+              echo "There is at least one rule with either fail or unknown result"
+            ;;
+            *)
+              >&2 echo "openscap returned an unexpected exit status of $OSCAP_EXIT_CODE"
+              exit "$OSCAP_EXIT_CODE"
+            ;;
+          esac
+      - name: Convert xml to hdf
+        run: |
+          # shellcheck shell=sh
+          set -eu
+          saf convert xccdf_results2hdf -i "openscap-report.xml" -o openscap-report.hdf
+      - name: Convert hdf to sarif
+        run: |
+          # shellcheck shell=sh
+          set -eu
+          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 sarif-multitool convert -t Hdf -o openscap-report.sarif openscap-report.hdf.json
+      - name: filter results that shouldn't be GitHub security alerts
+        # Hopefully GitHub adds support for SARIF's "kind" eliminating the need for this step: https://github.com/orgs/community/discussions/65477
+        run: |
+          # shellcheck shell=sh
+          set -eu
+          jq 'del(.runs[].results[] | select(.kind == "notApplicable" or .kind == "pass" or .kind == "informational" ))' openscap-report.sarif > filtered.sarif
+          mv filtered.sarif openscap-report.sarif
+      - name: Upload reports
+        if: success() || failure() # always run even if the previous step fails
+        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
+        with:
+          name: openscap-reports
+          path: |
+            openscap-report.html
+            openscap-report.xml
+            openscap-report.hdf.json
+            openscap-report.sarif
+      - name: Upload SARIF file
+        uses: github/codeql-action/upload-sarif@461ef6c76dfe95d5c364de2f431ddbd31a417628 # v3
+        # Results are generated only on a success or failure
+        # this is required since GitHub by default won't run the next step
+        # when the previous one has failed. Security checks that do not pass will 'fail'.
+        # An alternative is to add `continue-on-error: true` to the previous step
+        if: success() || failure()
+        with:
+          sarif_file: openscap-report.sarif
