ooooooooooooo
ooooooooooooooooo

diff --git a/.github/workflows/dockertest.yml b/.github/workflows/dockertest.yml
--- a/.github/workflows/dockertest.yml
+++ b/.github/workflows/dockertest.yml
@@ -167,7 +167,7 @@ jobs:
         name: Make the Grype JSON into an HDF file
         run: |
           set -eu
-          saf convert anchoregrype2hdf -i grype.json -o grype-results.hdf.json
+          saf convert anchoregrype2hdf -i grype-results.json -o grype-results.hdf.json
       -
         name: Okay so what happened
         run: |
@@ -177,8 +177,17 @@ jobs:
         name: Make the HDF file into a CSV
         run: |
           set -eu
-          saf convert anchoregrype2hdf -i grype.json -o grype-results.hdf.json
-
+          saf convert hdf2csv -i grype-results.hdf.json -o grype-results.csv
+      -
+        name: Upload reports
+        if: success() || failure() # always run even if the previous step fails
+        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
+        with:
+          name: trivy-results
+          path: |
+            grype.json
+            grype-results.hdf.json
+            grype-results.csv
 
 
   #trivy:
