tttttttttttttttttttttttttttttt
tttttttttttttt

diff --git a/.github/workflows/dockertest.yml b/.github/workflows/dockertest.yml
--- a/.github/workflows/dockertest.yml
+++ b/.github/workflows/dockertest.yml
@@ -115,75 +115,57 @@ jobs:
   #        path: |
   #          openscap-report.xml
 
-  # Grype currently busted, see https://github.com/anchore/scan-action/issues/378 , is to be fixed
-  # I could probably fix it looking at the code but that isn't my mandate.
+
   #grype:
   #  needs: build
   #  runs-on: ubuntu-latest
+  #  env:
+  #    MITRE_SAF_VERSION: "1.4.14"
   #  steps:
   #    -
-  #      name: Scan image with Grype
-  #      uses: anchore/scan-action@v4.1.2
-  #      id: grypescan
-  #      with:
-  #        registry-username: ${{ vars.DOCKERHUB_USERNAME }}
-  #        registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
-  #        image: ${{ env.IMAGE_NAME }}
-  #        fail-build: false
+  #      name: Install prerequisites
+  #      run: |
+  #        set -eu
+  #        sudo curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin
+  #        sudo apt-get install -y npm
+  #        # Specify the sinon version to use.
+  #        # Remove sinon from this line when sinon 16.1.2 (or later) is released, or when using MITRE_SAF_VERSION that includes https://github.com/mitre/saf/pull/1919
+  #        npm install -g sinon@16.1.0 "@mitre/saf@${MITRE_SAF_VERSION}"
   #    -
-  #      name: upload Anchore scan SARIF report
-  #      uses: github/codeql-action/upload-sarif@v2
+  #      name: Login to Docker Hub
+  #      uses: docker/login-action@v3
   #      with:
-  #        sarif_file: ${{ steps.grypescan.outputs.sarif }}
-
-  grype:
-    needs: build
-    runs-on: ubuntu-latest
-    env:
-      MITRE_SAF_VERSION: "1.4.14"
-    steps:
-      -
-        name: Install prerequisites
-        run: |
-          set -eu
-          sudo curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin
-          sudo apt-get install -y npm
-          # Specify the sinon version to use.
-          # Remove sinon from this line when sinon 16.1.2 (or later) is released, or when using MITRE_SAF_VERSION that includes https://github.com/mitre/saf/pull/1919
-          npm install -g sinon@16.1.0 "@mitre/saf@${MITRE_SAF_VERSION}"
-      -
-        name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ vars.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      # grype chainguard/wolfi-base -o json --file grype-results.json
-      # grype ${{ env.IMAGE_NAME }} -o json --file grype-results.json
-      -
-        name: Grype scan
-        run: |
-          set -eu
-          grype ${{ env.IMAGE_NAME }} -o json --file grype-results.json
-      -
-        name: Make the Grype JSON into an HDF file
-        run: |
-          set -eu
-          saf convert anchoregrype2hdf -i grype-results.json -o grype-results.hdf.json
-      -
-        name: Make the HDF file into a CSV
-        run: |
-          set -eu
-          saf convert hdf2csv -i grype-results.hdf.json -o grype-results.csv
-      -
-        name: Upload reports
-        if: success() || failure() # always run even if the previous step fails
-        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
-        with:
-          name: grype-results
-          path: |
-            grype-results.json
-            grype-results.hdf.json
-            grype-results.csv
+  #        username: ${{ vars.DOCKERHUB_USERNAME }}
+  #        password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #    # grype chainguard/wolfi-base -o json --file grype-results.json
+  #    # grype ${{ env.IMAGE_NAME }} -o json --file grype-results.json
+  #    -
+  #      name: Grype scan
+  #      run: |
+  #        set -eu
+  #        grype ${{ env.IMAGE_NAME }} -o json --file grype-results.json
+  #    -
+  #      name: Make the Grype JSON into an HDF file
+  #      run: |
+  #        set -eu
+  #        saf convert anchoregrype2hdf -i grype-results.json -o grype-results.hdf.json
+  #    # Converting HDF to CSV is currently busted,
+  #    # https://github.com/mitre/saf/issues/2925 for more info.
+  #    #-
+  #    #  name: Make the HDF file into a CSV
+  #    #  run: |
+  #    #    set -eu
+  #    #    saf convert hdf2csv -i grype-results.hdf.json -o grype-results.csv
+  #    -
+  #      name: Upload reports
+  #      if: success() || failure() # always run even if the previous step fails
+  #      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
+  #      with:
+  #        name: grype-results
+  #        path: |
+  #          grype-results.json
+  #          grype-results.hdf.json
+  #          grype-results.csv
 
 
   #trivy:
@@ -264,6 +246,21 @@ jobs:
   #        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
   #      with:
   #        image: ${{ env.IMAGE_NAME }}
+
+  snyk:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      -
+        name: Install prerequisites
+        run: |
+          curl --compressed https://downloads.snyk.io/cli/stable/snyk-linux -o snyk
+          sudo chmod +x ./snyk
+          sudo mv ./snyk /usr/local/bin/
+      -
+        name: Signs of life
+        run: |
+          snyk --version
 
   #clam:
   #  needs: build
