bbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbb

diff --git a/.github/workflows/dockertest.yml b/.github/workflows/dockertest.yml
--- a/.github/workflows/dockertest.yml
+++ b/.github/workflows/dockertest.yml
@@ -135,79 +135,88 @@ jobs:
   #      uses: github/codeql-action/upload-sarif@v2
   #      with:
   #        sarif_file: ${{ steps.grypescan.outputs.sarif }}
-
-  trivy:
+  
+  grype:
     needs: build
-    permissions:
-      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
-      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
     runs-on: ubuntu-latest
-    env:
-      TRIVY_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
-      TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
-      MITRE_SAF_VERSION: "1.4.14"
     steps:
       -
         name: Install prerequisites
         run: |
-          # shellcheck shell=sh
           set -eu
-          sudo apt-get install -y npm
-          # Specify the sinon version to use.
-          # Remove sinon from this line when sinon 16.1.2 (or later) is released, or when using MITRE_SAF_VERSION that includes https://github.com/mitre/saf/pull/1919
-          npm install -g sinon@16.1.0 "@mitre/saf@${MITRE_SAF_VERSION}"
+          sudo curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin
       -
-        name: Scan image
-        uses: aquasecurity/trivy-action@0.24.0
-        with:
-          image-ref: ${{ env.IMAGE_NAME }}
-          #image-ref: 'redhat/ubi9:9.4'
-          template: '@/contrib/asff.tpl'
-          format: 'template'
-          output: 'trivy-results.json'
-      -
-        name: Make the Trivy ASFF JSON into an HDF file
+        name: Signs of life
         run: |
           set -eu
-          saf convert trivy2hdf -i trivy-results.json -o trivy-results
-      -
-        name: What the actual heck
-        run: |
-          set -eu
-          ls -latr
-      -
-        name: What the actual heck 2
-        run: |
-          set -eu
-          ls -latr ${{ github.workspace }}/trivy-results/
-      # OKAY SO WE NEED TO TEST FOR WHEN WE HAVE ZERO RESULTS IN THE TRIVY FILE BECAUSE THAT IS A THING THAT HAPPENS.
-      # Because the response for zero results is extremely well defined, this means we can use if/else logic to determine our path forward.
-      # We will first test for the case of zero vulnerabilities; if the file doesn't come back with zero vulns, we move forward with conversion.
-      - name: Test results and either create a stub file or convert them.
-        run: |
-          if grep -zoP '...."Findings": \[\n*....\]\n' trivy-results.json; then
-            echo THE GREP WORKS
-          else
-            echo CONVERTING FILE
-          fi
-      #cp '${{ github.workspace }}/trivy-results/aquasecurity - aquasecurity.json' ${{ github.workspace }}/trivy-results.hdf.json
-      # Converting HDF to CSV is currently busted,
-      # https://github.com/mitre/saf/issues/2925 for more info.
-      #-
-      #  name: Make the HDF file into a CSV
-      #  run: |
-      #    set -eu
-      #    saf convert hdf2csv -i trivy-results.hdf.json -o trivy-results.csv
-      -
-        name: Upload reports
-        if: success() || failure() # always run even if the previous step fails
-        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
-        with:
-          name: trivy-results
-          path: |
-            trivy-results.hdf.json
-            trivy-results.hdf
-            trivy-results.csv
+          grype --version
+
+  #trivy:
+  #  needs: build
+  #  permissions:
+  #    security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
+  #    actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
+  #  runs-on: ubuntu-latest
+  #  env:
+  #    TRIVY_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
+  #    TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
+  #    MITRE_SAF_VERSION: "1.4.14"
+  #  steps:
+  #    -
+  #      name: Install prerequisites
+  #      run: |
+  #        # shellcheck shell=sh
+  #        set -eu
+  #        sudo apt-get install -y npm
+  #        # Specify the sinon version to use.
+  #        # Remove sinon from this line when sinon 16.1.2 (or later) is released, or when using MITRE_SAF_VERSION that includes https://github.com/mitre/saf/pull/1919
+  #        npm install -g sinon@16.1.0 "@mitre/saf@${MITRE_SAF_VERSION}"
+  #    -
+  #      name: Scan image
+  #      uses: aquasecurity/trivy-action@0.24.0
+  #      with:
+  #        #image-ref: ${{ env.IMAGE_NAME }}
+  #        image-ref: 'redhat/ubi9:9.4'
+  #        template: '@/contrib/asff.tpl'
+  #        format: 'template'
+  #        output: 'trivy-results.json'
+  #    -
+  #      name: Make the Trivy ASFF JSON into an HDF file
+  #      run: |
+  #        set -eu
+  #        saf convert trivy2hdf -i trivy-results.json -o trivy-results
+  #    # OKAY SO WE NEED TO TEST FOR WHEN WE HAVE ZERO RESULTS IN THE TRIVY FILE BECAUSE THAT IS A THING THAT HAPPENS.
+  #    # Because the response for zero results is extremely well defined, this means we can use if/else logic to determine our path forward.
+  #    # We will first test for the case of zero vulnerabilities; if the file doesn't come back with zero vulns, we move forward with conversion.
+  #    - name: Test results and either create a stub file or convert them.
+  #      run: |
+  #        set -eu
+  #        if grep -zoP '...."Findings": \[\n*....\]\n' trivy-results.json; then
+  #          echo THE GREP WORKS
+  #          echo YOU NEED TO FIGURE OUT WHAT YOU WANT TO PASS FOR CSV HERE
+  #          echo TREMENDOUS EFFORT
+  #        else
+  #          echo CONVERTING FILE - THIS IS GOING TO FAIL UNTIL MITRE FIXES THINGS
+  #          cp '${{ github.workspace }}/trivy-results/aquasecurity - aquasecurity.json' ${{ github.workspace }}/trivy-results.hdf.json
+  #          saf convert hdf2csv -i trivy-results.hdf.json -o trivy-results.csv
+  #        fi
+  #    # Converting HDF to CSV is currently busted,
+  #    # https://github.com/mitre/saf/issues/2925 for more info.
+  #    #-
+  #    #  name: Make the HDF file into a CSV
+  #    #  run: |
+  #    #    set -eu
+  #    #    saf convert hdf2csv -i trivy-results.hdf.json -o trivy-results.csv
+  #    -
+  #      name: Upload reports
+  #      if: success() || failure() # always run even if the previous step fails
+  #      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
+  #      with:
+  #        name: trivy-results
+  #        path: |
+  #          trivy-results.hdf.json
+  #          trivy-results.hdf
+  #          trivy-results.csv
 
   #snyk:
   #  needs: build
